---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.1
env:
  - PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
matrix:
  fast_finish: true
  include:
    -
      env: CHECK=rubocop
    -
      env: CHECK="syntax lint"
    -
      env: CHECK=metadata_lint
    -
      env: CHECK=spec DEPLOY_TO_FORGE=yes
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
      rvm: 2.1.9
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: glorpen
  password:
    secure: "F92mqId5/ABiwpYw7NTCUftmOAHnsqX8XTPZaSFW6rGRHeCY2tKK/m/JBeqjOZUXZVAo/4eLgAygcXZ7R6e98XksLQTsqhDEOPUkaSR84EUPBr2JYyBcwEJ0+0NZV6lVD5JJbEKZWhN3xZ+Auca4LqH/sCuWBYa3jBAIJmM2pYovSAJoiquX3/erjw3dY0jGXPTu/KZojPVjyWj3u/b/ikIBrU+1EV+ZdhjJ/cZBIzKptDtC/6CSn22EUdEUiYETOf/fit1GM4HEdg9zjEJjXCsJ65vuaq50dEa2Ckbz+8H5pFrSuxe5U7hK3SyZWNoWBpf4LmNckU5X78zyTMAvXsQYBzZ76NyabI9f9rIlaeXu8XlZ/EJxqZqT9HNiWYe8+ytlEIAZzzodMJIglqL4GXifwcwLhIttj8M1eyJgfIOUCoHj4+FlhfESwVYcgREpcHxAAIwoiY+j/f4FfNapN70XKkOBWHlal0Qa76a6bZZKbmEASbvrLXOG0itj0sykb4SkICMQZxCb5+meFa2I8G2sPj/xjK/BhwzQ8uJbZXO0C9WU6HLbh2TzcLv3p2ikFm5lYUMxiAMeCjpO2nYDdwayuKUxaRvq/YS157qwoJfa78RyYqDJgi2zZxQdBche9FXo+GCrBtFnbHYTrZnc/kI69clsYagtR+2FKM8gz0M="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
